@startsalt standings
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>🔍 GET - Strip color <color:#c1c0c0><size:16>#c1c0c0
		{+
			<back:#242429>[<img:../logo.png>    <b><color:#ffffff><size:14>VNMC(year) - Final Standings]
			.
			<color:#ffffff><size:14>🥇 **(player_name)**
			<color:#ffffff><size:14>🥈 **(player_name)**
			<color:#ffffff><size:14>🥉 **(player_name)**
			<color:#ffffff><size:14>//(rank)//: **(player_name)**
			<color:#ffffff><size:14>//(rank-rank)//: **(player_name)**, **(player_name)** /' if rank is a range '/
			/' rest of players '/
		}
	}
@endsalt