@startsalt standings
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>🔍 GET - Strip color <color:#c1c0c0><size:16>#c1c0c0
		{+
			<back:#242429>[<img:../logo.png>    <b><color:#ffffff><size:14>VNMC(year) - Final Standings]
			.
			<color:#ffffff><size:14>🥇 <color:#4c8cda>__(player_name)__
			<color:#ffffff><size:14>🥈 <color:#4c8cda>__(player_name)__
			<color:#ffffff><size:14>🥉 <color:#4c8cda>__(player_name)__
			<color:#ffffff><size:14>//(rank)//: <color:#4c8cda>__(player_name)__
			<color:#ffffff><size:14>//(rank-rank)//: <color:#4c8cda>__(player_name)__, <color:#4c8cda>__(player_name)__ /' if rank is a range '/
			/' rest of players '/
		}
	}
@endsalt