@startsalt standings
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>🔍 GET
		{+
			==== <color:#ffffff>VNMC(year) - Final Standings
			.
			<color:#ffffff>🥇 **(player_name)**
			<color:#ffffff>🥈 **(player_name)**
			<color:#ffffff>🥉 **(player_name)**
			<color:#ffffff>//(rank)//: **(player_name)**
			<color:#ffffff>//(rank-rank)//: **(player_name)**, **(player_name)** /' if rank is a range '/
			/' rest of players '/
		}
	}
@endsalt