@startsalt exception
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{+
		<b><color:#ffffff><size:16>❌ Error occurred!</b>
		.
		<color:#ffffff><size:14>(error_code) - (reason)
		.
		<color:#ffffff><size:14>(error_message)
	}
@endsalt