@startsalt exception
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>Strip color <color:#dd2f45><size:16>#dd2f45
		{+
			<b><color:#ffffff><size:16>❌ Error occurred!
			.
			<color:#ffffff><size:14>(error_code) - (reason)
			.
			<color:#ffffff><size:14>(error_message)
		}
	}
@endsalt