@startsalt mappool
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>🔍 GET
		{+
			<b><color:#ffffff><size:14>VNMC(year) - (full_round_name) Mappool</b>
			.
			<b><color:#ffffff>🍚 RC maps:</b>
			.
			<color:#ffffff>**(code)** - <color:#4c8cda>__(title) [(diff_name)]__
			<color:#ffffff>**(code)** - <color:#4c8cda>__(title) [(diff_name)]__
			/' rest of RC maps '/ .
			<b><color:#ffffff>🍲 HB maps:</b>
			.
			<color:#ffffff>**(code)** - <color:#4c8cda>__(title) [(diff_name)]__
			<color:#ffffff>**(code)** - <color:#4c8cda>__(title) [(diff_name)]__
			/' rest of HB maps '/ .
			<b><color:#ffffff>🍜 LN maps:</b>
			.
			<color:#ffffff>**(code)** - <color:#4c8cda>__(title) [(diff_name)]__
			<color:#ffffff>**(code)** - <color:#4c8cda>__(title) [(diff_name)]__
			/' rest of LN maps '/ .
			<b><color:#ffffff>🎶 SV Maps:</b>
			.
			<color:#ffffff>**(code)** - <color:#4c8cda>__(title) [(diff_name)]__
			<color:#ffffff>**(code)** - <color:#4c8cda>__(title) [(diff_name)]__
			/' rest of SV maps '/ .
			<b><color:#ffffff>🔥 Tiebreaker:</b>
			<color:#ffffff>**(code)** - <color:#4c8cda>__(title) [(diff_name)]__
		}
		.
		= <color:#ffffff>📄 POST
		{+
			<b><color:#ffffff><size:16>✅ Successfully created (full_round_name) mappool!</b>
		}
		.
		= <color:#ffffff>🗑️ DELETE
		{+
			<b><color:#ffffff><size:16>✅ Successfully deleted (full_round_name) mappool!</b>
		}
	}
@endsalt