@startsalt mappool
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>🔍 GET
		{+
			<b><color:#ffffff><size:14>VNMC(year) - (full_round_name) Mappool</b>
			.
			<color:#ffffff><back:#6fa8dc><color:#000000>**(code)**</back> - (title) [(diff_name)]
			/' rest of RC maps '/ .
			<color:#ffffff><back:#8e7cc3><color:#000000>**(code)**</back> - (title) [(diff_name)]
			/' rest of HB maps '/ .
			<color:#ffffff><back:#ffd966><color:#000000>**(code)**</back> - (title) [(diff_name)]
			/' rest of LN maps '/ .
			<color:#ffffff><back:#e06666><color:#000000>**(code)**</back> - (title) [(diff_name)]
			/' rest of SV maps '/ .
			<color:#ffffff><back:#d9d9d9><color:#000000>**(code)**</back> - (title) [(diff_name)]
		}
		.
		= <color:#ffffff>📄 POST
		{+
			<b><color:#ffffff><size:16>✅ Successfully created (full_round_name) mappool!</b>
		}
		.
		= <color:#ffffff>🗑️ DELETE
		{+
			<b><color:#ffffff><size:16>✅ Successfully deleted (full_round_name) mappool!</b>
		}
	}
@endsalt