@startsalt matches
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff><&magnifying-glass> GET
		{+
			==== <color:#ffffff>VNMC(year) - (full_round_name) - Match List
			.
			<color:#ffffff>**Match (match_id)**: <:1f7e5:> **(player_1_name)** - #(seed) (time - remaining_time) **(player_2_name)** - #(seed) <:1f7e6:> /' blue and red squares for team sides, not supported :< '/
			<color:#ffffff>**Match (match_id)**: <:1f7e5:> **(player_1_name)** - #(seed) **6** - 0 **(player_2_name)** - #(seed) <:1f7e6:> /' if match is completed '/
			/' rest of matches '/.
		}
		.
		= <color:#ffffff><&pencil> PUT
		{+
			== <color:#ffffff><&check> Successfully fetched matches for VNMC(year)!	
		}
	}
@endsalt