@startsalt matches
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>🔍 GET
		{+
			<b><color:#ffffff><size:14>VNMC(year) - (full_round_name) - Match List</b>
			.
			<color:#ffffff><size:14>**Match (match_id)**:  🟥 **(player_1_name)** - #(seed) (time - remaining_time) **(player_2_name)** - #(seed) 🟦
			<color:#ffffff><size:14>**Match (match_id)**:  🟥 **(player_1_name)** - #(seed) **6** - 0 **(player_2_name)** - #(seed) 🟦 /' if match is completed '/
			/' rest of matches '/.
		}
		.
		= <color:#ffffff>✏️ PUT
		{+
			<b><color:#ffffff><size:16>✅ Successfully fetched matches for VNMC(year)!</b>
		}
	}
@endsalt