@startsalt mappool
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff><&document> POST
		{+
			== <color:#ffffff><&check> Successfully created tournament VNMC(year)!
		}
	}
@endsalt