@startsalt mappool
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>📄 POST
		{+
			<b><color:#ffffff><size:16>✅ Successfully created tournament VNMC(year)!
		}
	}
@endsalt