@startsalt mappool
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>📄 POST
		{+
			== <color:#ffffff>✅ Successfully created tournament VNMC(year)!
		}
	}
@endsalt