@startsalt map
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>🔍 GET - Strip color <color:#c1c0c0><size:16>#c1c0c0
		{+
			<back:#242429>[<img:../logo.png>    <b><color:#ffffff><size:14>VNMC(year) - (full_round_name) - (code) {<img:https://dummyimage.com/150x50/ffffff/000000&text=(map_img)>}]
			<b><color:#4c8cda><size:16>__(title) [(diff_name)]__
			.
			<color:#ffffff><size:14>(artist)
			.
			<color:#ffffff><size:14>**SR**: (sr)
			<color:#ffffff><size:14>**BPM**: (bpm)
			<color:#ffffff><size:14>**OD**: (od)
			<color:#ffffff><size:14>**HP**: (hp)
			<color:#ffffff><size:14>**Length**: (mm:ss) /' use drain time '/
		}
		.
		= <color:#ffffff>📄 POST - Strip color <color:#77b255><size:16>#77b255
		{+
			<b><color:#ffffff><size:16>✅ Successfully added new map to pool (full_round_name)!
			.
			<color:#ffffff><size:14>**Map Code**: (code)
			<color:#ffffff><size:14>**Map ID**: (id)
		}
		.
		= <color:#ffffff>✏️ PUT - Strip color <color:#77b255><size:16>#77b255
		{+
			<b><color:#ffffff><size:16>✅ Successfully updated map (code) in pool (full_round_name)!
			.
			<color:#ffffff><size:14>**New Map ID**: (id)
		}
		.
		= <color:#ffffff>🗑️ DELETE - Strip color <color:#77b255><size:16>#77b255
		{+
			<b><color:#ffffff><size:16>✅ Successfully deleted map (code) in pool (full_round_name)!</b>
		}
	}
@endsalt