@startsalt player
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>🔍 GET
		{+
			<b><color:#ffffff><size:14>VNMC(year) - Player List</b>
			.
			*<color:#ffffff><size:14>**(name)** - ((#rank))
			/' rest of players '/ .
		}
		.
		= <color:#ffffff>📄 POST
		{+
			<b><color:#ffffff><size:16>✅ Successfully registered for VNMC(year) as (player_name)!</b>
		}
		.
		= <color:#ffffff>🗑️ DELETE
		{+
			<b><color:#ffffff><size:16>✅ Successfully left the tournament.</b>
			.
			<color:#ffffff><size:14>We are so sad to see you leave 😭😭😭
		}
	}
@endsalt