@startsalt staff
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>🔍 GET
		{+
			<b><color:#ffffff><size:14>VNMC(year) - Staff List
			.
			<color:#ffffff><size:14>**(role)**
			*<color:#ffffff><size:14>(name)
			/' rest of roles and members '/ .
		}
		.
		= <color:#ffffff>📄 POST
		{+
			<b><color:#ffffff><size:16>✅ Successfully registered new (full_staff_role) to (player_name)!
		}
		.
		= <color:#ffffff>✏️ PUT
		{+
			<b><color:#ffffff><size:16>✅ Successfully switched (player_name)'s role to (new_full_staff_role) from (old_full_staff_role)!
		}
		.
		= <color:#ffffff>🗑️ DELETE
		{+
			<b><color:#ffffff><size:16>✅ Successfully deleted (full_staff_role) role for (player_name)!
		}
	}
@endsalt