@startsalt staff
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>🔍 GET
		{+
			==== <color:#ffffff>VNMC(year) - Staff List
			.
			<color:#ffffff>**(role)**
			*<color:#ffffff>(name)
			/' rest of roles and members '/ .
		}
		.
		= <color:#ffffff>📄 POST
		{+
			== <color:#ffffff>✅ Successfully registered new (full_staff_role) to (player_name)!
		}
		.
		= <color:#ffffff>✏️ PUT
		{+
			== <color:#ffffff>✅ Successfully switched (player_name)'s role to (new_full_staff_role) from (old_full_staff_role)!	
		}
		.
		= <color:#ffffff>🗑️ DELETE
		{+
			== <color:#ffffff>✅ Successfully deleted (full_staff_role) role for (player_name)!
		}
	}
@endsalt