@startsalt login
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		{+
			<b><color:#ffffff><size:16>Please follow this link: <color:#4c8cda>__(auth_link)__ <color:#ffffff>and click on the **Authorize** button.
			.
			<color:#ffffff><size:14>⏳ Waiting for authentication...
		}
		.
		{+
			<b><color:#ffffff><size:16>✅ Successfully authenticated as (player_name)!
		}
		.
		{+
			<b><color:#ffffff><size:16>❌ Authentication failed. Please try again.
		}
	}
@endsalt