@startsalt match
	<style>
		saltDiagram {
			BackgroundColor #242429
		}
	</style>
	{
		= <color:#ffffff>🔍 GET - Strip color <color:#c1c0c0><size:16>#c1c0c0
		{+
			<b><color:#ffffff><size:14>VNMC(year) - (full_round_name) - Match (match_id)
			.
			<b><color:#4c8cda><size:16>__(player_1_name) VS (player_2_name)__
			.
			<color:#ffffff><back:#323336>M/dd/yyyy h:mm a <color:#ffffff><back:#323336>... ago /' discord's US formatting. for notation definitions refer: https://date-fns.org/v4.1.0/docs/format '/
			.
			<b><color:#ffffff><size:14>📊 Results
			<color:#4c8cda><size:14>🟥 __(player_1_name)__ <color:#ffffff>(#seed) **6** - 0 <color:#4c8cda>__(player_2_name)__ <color:#ffffff>(#seed) 🟦
			.
			<b><color:#ffffff><size:14>🎲 Rolls
			<color:#4c8cda><size:14>🟥 __(player_1_name)__ <color:#ffffff>(#seed) 69 - **96** <color:#4c8cda>__(player_2_name)__ <color:#ffffff>(#seed) 🟦
			<color:#ffffff><size:14>🟦 chose to protect second.
			.
			<b><color:#ffffff><size:14>🚫🛡️ Protect and Ban Phase
			<color:#ffffff><size:14>🟥 protects (code)
			<color:#ffffff><size:14>🟦 bans (code)
			/' rest of protects and bans '/
			.
			<b><color:#ffffff><size:14>⚔️ Match Rundown
			<color:#ffffff><size:14>🟥 picked (code) >> 🟥 won
			<color:#ffffff><size:14>🟦 picked (code) >> 🟥 won
			/' rest of picks '/
			.
			<color:#ffffff><size:12>Referee: (referee_name)
		}
		.
		= <color:#ffffff>✏️ PUT /ref - Strip color <color:#77b255><size:16>#77b255
		{+
			<b><color:#ffffff><size:16>✅ Successfully assigned referee (referee_name) to match (match_id)!
		}
		.
		= <color:#ffffff>🗑️ DELETE /ref - Strip color <color:#77b255><size:16>#77b255
		{+
			<b><color:#ffffff><size:16>✅ Successfully removed referee for match (match_id)!
		}
		.
		= <color:#ffffff>✏️ PUT /time - Strip color <color:#77b255><size:16>#77b255
		{+
			<b><color:#ffffff><size:16>✅ Successfully rescheduled match (match_id) to (new_time)!
		}
	}
@endsalt