Year:
  name: year
  in: path
  required: true
  schema:
    type: number
Round:
  name: round
  in: path
  required: true
  schema:
    type: string
    enum:
      - qual
      - ro64
      - ro32
      - ro16
      - qf
      - sf
      - f
      - gf
Event:
  name: event
  in: path
  required: true
  schema:
    type: string
    enum:
      - registration
      - qual
      - ro64
      - ro32
      - ro16
      - qf
      - sf
      - f
      - gf
MapCode:
  name: code
  in: path
  required: true
  schema:
    type: string
    pattern: ^(?:[1-5]|(?:RC[1-7]|LN[1-4]|HB[1-3]|SV[1-2])|TB)$
Id:
  name: id
  in: path
  required: true
  schema:
    type: string
Role: # add enum later on?
  name: role
  in: path
  required: true
  schema:
    type: string
Name:
  name: name
  in: query
  required: false
  schema:
    type: string
Sort:
  name: sort
  in: query
  required: false
  schema:
    type: string
    enum:
      - rank
      - reg_time
Limit:
  name: limit
  in: query
  required: false
  schema:
    type: integer